@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTI4OTU1OTJ9.OKPqPu7KmKBMtr4W42SjXcsmnuvfC9LINxP2aE4u0Mc

### create
POST http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "product_id": 1,
  "quantity": 2
}

### index
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}


### show
GET http://localhost:3000/orders/4.json
Authorization: Bearer {{jwt}}
